import Head from 'next/head'
import Image from 'next/image'
import ContentCard from '../components/ContentCard'
import Grid from '@mui/material/Grid';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import PhoneIcon from '@mui/icons-material/Phone';
import FavoriteIcon from '@mui/icons-material/Favorite';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import { useState } from 'react';

export default function Home() {

  const [value, setValue] = useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };


  return (
    <>
    
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        direction="column"
        justifyContent="center"
        alignItems="center"
      >
        <Grid item>
          <Tabs value={value} onChange={handleChange} aria-label="icon tabs example">
            <Tab icon={<CloudUploadIcon />} aria-label="img-upload" label="업로드" iconPosition="start" />
            <Tab icon={<FavoriteIcon />} aria-label="favorite" />
          </Tabs>
        </Grid>
      </Grid>
    </>
  )
}
