import Head from 'next/head'
import ContentCard from '@/components/ContentCard';
import Container from '@mui/material/Container'

export default function Home({ cardObjArray }) {
  return (
    <>
      <Head>
        <title>
          몰라로이드
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">

        {cardObjArray.length > 0? cardObjArray.map((cardObj, index) => ( 
          <div className='card-container' key={index}>
            <ContentCard
              imageSrc={cardObj.image}
              audioSrc={cardObj.audio}
              text={cardObj.text}
            />
          </div>
      )):''}
        
      </Container>

      <style jsx>{`
          .card-container {
            margin-top: 20px;
          }
        
        `}</style>
    </>
  )
}

export async function getServerSideProps(context) {

  let cardObjArray;
  const response = await fetch('http://130.162.135.161:3000/api/image',{
    method: 'GET',    
    headers: {
          'Accept': 'application/json'
        }
    },

  );
  if (response.ok) {
    const data = await response.json();
    cardObjArray = data;
  } 
  return {
    props: {
      cardObjArray: cardObjArray,
    }, 
  }
}
